---
namespace: moodle
resources:
  - ../../base
configMapGenerator:
  - name: nginx-config
    namespace: moodle
    files:
      - default.conf=serverconfig/default.conf
  - name: php-ini
    namespace: moodle
    files:
      - php.ini=serverconfig/php.ini
secretGenerator:
  - name: config-php
    namespace: moodle
    files:
      - config.php=serverconfig/config.php
images:
  - name: moodle-sample
    newName: us-central1-docker.pkg.dev/dev-moodle-361614/moodle-repo/moodle
    newTag: v2
