kind: ConfigMap
apiVersion: v1
metadata:
  namespace: moodle
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name default_server;
        root /var/www/html;
        index index.html index.htm index.php;
        client_max_body_size 500M;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ /\.git {
            deny all;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info  ^(.+\.php)(/.+)$;
            fastcgi_index            index.php;
            fastcgi_pass             127.0.0.1:9000;
            include                  fastcgi_params;
            fastcgi_read_timeout     240;
            fastcgi_param   PATH_INFO       $fastcgi_path_info;
            fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
