apiVersion: v1
kind: Service
metadata:
  name: moodle
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "my-backendconfig"}'
spec:
  ports:
    - name: moodle-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 8
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /README.txt
    port: 80
