apiVersion: v1
kind: Service
metadata:
  namespace: moodle
  name: redis
spec:
  ports:
    - name: redis-port
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: moodle
    tier: cache
  sessionAffinity: None
  type: ClusterIP
